#!/usr/bin/python

from glob import glob
import os
import re
import sys

def get_homebrew_paths():
    """Get the installed Homebrew PHP paths as a dict, keyed on version."""
    paths = glob('/usr/local/Cellar/php[0-9][0-9]/*/bin')

    result = dict()
    for path in paths:
        version = get_version_from_path(path)
        result[version] = path
    return result

def get_version_from_path(path):
    """Take a string like '/usr/local/Cellar/phpxy/a.b.c/bin', remove the leading
    24 characters, and the trailing 4. Hacky, but quick."""
    return path[24:][0:-4]

def select_version_path(path):
    files = get_files_for_path(path)
    for file_name in files:
        print 'alias %s=%s/%s' % (file_name, path, file_name)

def get_files_for_path(path):
    """Get the files we should symlink from a given path."""
    ignore_files = ['phar.phar']
    return [x for x in os.listdir(path) if x not in ignore_files]

paths = get_homebrew_paths()

if len(sys.argv) == 1:
    for version in sorted(paths.iterkeys()):
        print version
else:
    # Reverse sort so that '5.5' will match newest-installed version of 5.5.
    version_prefix = sys.argv[1]
    for version in sorted(paths.iterkeys(), reverse=True):
        if version[0:len(version_prefix)] == version_prefix:
            select_version_path(paths[version])
            sys.exit(0)
    sys.exit(1)

sys.exit(0)
